
# General configs
baseurl: ''
url: ''
lang: pt_BR

# SEO cofigs
head:
  title: luppa
  description: o mediador de gastos reverso
  author: luppa
  # github: username
  # codepen: username
  # linkedin: username
  themeColor: "#8caee0"
  imagePathMain: /assets/img/luppa-with-background-blue.png

  jsonld:
    type: person
    name: luppa
    # url: example@example.com.br
    # email: your-email@domain.com

  # twitter:
  #   author: Your username

source: source
destination: _site

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src
